title: "Spark-EU"
description: "Spark-EU is a synth module designed for the Eurorack format. It is a clone of our own Spark-AE module."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
